import { Request, Response, NextFunction } from 'express';
import { AuthRequest } from '../middlewares/auth.middleware';
import { db } from '../config/firebase';
import { sendResponse } from '../utils/response';
import Joi from 'joi';

const taskSchema = Joi.object({
  title: Joi.string().required(),
  category: Joi.string().valid('DSA', 'Technical Skill', 'Aptitude', 'CS Fundamentals', 'Project', 'Revision', 'Optional').required(),
  priority: Joi.string().valid('Low', 'Medium', 'High').default('Medium'),
  estimatedDuration: Joi.number().min(0).default(60),
  status: Joi.string().valid('pending', 'completed', 'skipped', 'rescheduled', 'incomplete').default('pending'),
  date: Joi.string().pattern(/^\d{4}-\d{2}-\d{2}$/).required(),
  notes: Joi.string().allow('', null).optional(),
});

const updateTaskSchema = Joi.object({
  title: Joi.string().optional(),
  category: Joi.string().valid('DSA', 'Technical Skill', 'Aptitude', 'CS Fundamentals', 'Project', 'Revision', 'Optional').optional(),
  priority: Joi.string().valid('Low', 'Medium', 'High').optional(),
  estimatedDuration: Joi.number().min(0).optional(),
  status: Joi.string().valid('pending', 'completed', 'skipped', 'rescheduled', 'incomplete').optional(),
  date: Joi.string().pattern(/^\d{4}-\d{2}-\d{2}$/).optional(),
  notes: Joi.string().allow('', null).optional(),
});

// GET /api/v1/tasks?date=YYYY-MM-DD
export const getTasks = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const { date } = req.query;

    let tasksQuery: any = db.collection('users').doc(uid!).collection('tasks');

    if (date) {
      tasksQuery = tasksQuery.where('date', '==', date);
    }

    const snapshot = await tasksQuery.get();
    let tasks = snapshot.docs.map((doc: any) => ({ id: doc.id, ...doc.data() }));

    // Sort in memory to avoid requiring a composite index
    tasks.sort((a: any, b: any) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());

    sendResponse(res, 200, true, 'Tasks fetched successfully', tasks);
  } catch (error) {
    next(error);
  }
};

// POST /api/v1/tasks
export const createTask = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const { error, value } = taskSchema.validate(req.body);

    if (error) {
      sendResponse(res, 400, false, 'Validation Error', error.details.map(x => x.message));
      return;
    }

    const newTask = {
      ...value,
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const docRef = await db.collection('users').doc(uid!).collection('tasks').add(newTask);
    
    sendResponse(res, 201, true, 'Task created successfully', { id: docRef.id, ...newTask });
  } catch (error) {
    next(error);
  }
};

// PUT /api/v1/tasks/:taskId
export const updateTask = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const taskId = req.params.taskId;
    const { error, value } = updateTaskSchema.validate(req.body);

    if (error) {
      sendResponse(res, 400, false, 'Validation Error', error.details.map(x => x.message));
      return;
    }

    const taskRef = db.collection('users').doc(uid!).collection('tasks').doc(taskId as string);
    const taskDoc = await taskRef.get();

    if (!taskDoc.exists) {
      sendResponse(res, 404, false, 'Task not found');
      return;
    }

    const updates = {
      ...value,
      updatedAt: new Date().toISOString(),
    };

    await taskRef.update(updates);
    const updatedDoc = await taskRef.get();

    sendResponse(res, 200, true, 'Task updated successfully', { id: updatedDoc.id, ...updatedDoc.data() });
  } catch (error) {
    next(error);
  }
};

// DELETE /api/v1/tasks/:taskId
export const deleteTask = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const taskId = req.params.taskId;

    const taskRef = db.collection('users').doc(uid!).collection('tasks').doc(taskId as string);
    await taskRef.delete();

    sendResponse(res, 200, true, 'Task deleted successfully');
  } catch (error) {
    next(error);
  }
};

const generateTasksSchema = Joi.object({
  date: Joi.string().pattern(/^\d{4}-\d{2}-\d{2}$/).required(),
  technicalSkill: Joi.string().required(),
  csConcept: Joi.string().allow('', null).optional(),
});

// POST /api/v1/tasks/generate
export const generateDailyTasks = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const { error, value } = generateTasksSchema.validate(req.body);

    if (error) {
      sendResponse(res, 400, false, 'Validation Error', error.details.map(x => x.message));
      return;
    }

    const { date, technicalSkill, csConcept } = value;
    const targetDate = new Date(date);
    const dayOfWeek = targetDate.getDay(); // 0 = Sunday, 1 = Monday, ..., 6 = Saturday

    const tasksRef = db.collection('users').doc(uid!).collection('tasks');
    const existingTasksSnapshot = await tasksRef.where('date', '==', date).get();

    const alreadyGenerated = existingTasksSnapshot.docs.some(doc => doc.data().isAutoGenerated === true);

    if (alreadyGenerated) {
      sendResponse(res, 400, false, 'Tasks already generated for this date');
      return;
    }

    const tasksToCreate: any[] = [];
    const baseTask = {
      date,
      status: 'pending',
      isAutoGenerated: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    if (dayOfWeek >= 1 && dayOfWeek <= 5) {
      // Monday to Friday: 3 DSA, 1 hr Tech Skill, 30-45 mins Aptitude
      tasksToCreate.push({
        ...baseTask,
        title: 'Solve DSA Problem 1',
        category: 'DSA',
        priority: 'High',
        estimatedDuration: 45
      });
      tasksToCreate.push({
        ...baseTask,
        title: 'Solve DSA Problem 2',
        category: 'DSA',
        priority: 'High',
        estimatedDuration: 45
      });
      tasksToCreate.push({
        ...baseTask,
        title: 'Solve DSA Problem 3',
        category: 'DSA',
        priority: 'High',
        estimatedDuration: 45
      });
      tasksToCreate.push({
        ...baseTask,
        title: `Learn ${technicalSkill}`,
        category: 'Technical Skill',
        priority: 'High',
        estimatedDuration: 60
      });
      tasksToCreate.push({
        ...baseTask,
        title: 'Aptitude Practice',
        category: 'Aptitude',
        priority: 'Medium',
        estimatedDuration: 45
      });
    } else if (dayOfWeek === 6) {
      // Saturday: Optional Contests
      tasksToCreate.push({
        ...baseTask,
        title: 'Participate in LeetCode/CodeChef Contest',
        category: 'Optional',
        priority: 'Low',
        estimatedDuration: 120
      });
    } else if (dayOfWeek === 0) {
      // Sunday: Revision and Evaluation
      tasksToCreate.push({
        ...baseTask,
        title: 'Revise weak DSA problems from the week',
        category: 'Revision',
        priority: 'High',
        estimatedDuration: 60
      });
      tasksToCreate.push({
        ...baseTask,
        title: `Revise ${technicalSkill} concepts`,
        category: 'Revision',
        priority: 'High',
        estimatedDuration: 60
      });
      if (csConcept) {
        tasksToCreate.push({
          ...baseTask,
          title: `Study Core CS: ${csConcept}`,
          category: 'CS Fundamentals',
          priority: 'Medium',
          estimatedDuration: 60
        });
      }
    }

    const batch = db.batch();
    const createdTasks = [];

    for (const task of tasksToCreate) {
      const docRef = tasksRef.doc();
      batch.set(docRef, task);
      createdTasks.push({ id: docRef.id, ...task });
    }

    await batch.commit();

    sendResponse(res, 201, true, 'Daily tasks generated successfully', createdTasks);
  } catch (error) {
    next(error);
  }
};

// GET /api/v1/tasks/analytics/weekly?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
export const getTaskAnalytics = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const { startDate, endDate } = req.query;

    if (!startDate || !endDate) {
      sendResponse(res, 400, false, 'startDate and endDate are required');
      return;
    }

    const snapshot = await db.collection('users').doc(uid!)
      .collection('tasks')
      .where('date', '>=', startDate as string)
      .where('date', '<=', endDate as string)
      .get();

    const tasks = snapshot.docs.map(doc => doc.data());

    const total = tasks.length;
    const completed = tasks.filter(t => t.status === 'completed').length;
    const skipped = tasks.filter(t => t.status === 'skipped').length;
    const rescheduled = tasks.filter(t => t.status === 'rescheduled').length;
    const incomplete = tasks.filter(t => t.status === 'incomplete').length;
    const pending = tasks.filter(t => t.status === 'pending').length;

    sendResponse(res, 200, true, 'Analytics fetched successfully', {
      total,
      completed,
      skipped,
      rescheduled,
      incomplete,
      pending,
      completionPercentage: total > 0 ? Math.round((completed / total) * 100) : 0
    });
  } catch (error) {
    next(error);
  }
};

// GET /api/v1/tasks/analytics/heatmap?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
export const getDailyHeatmap = async (req: AuthRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const uid = req.user?.uid;
    const { startDate, endDate } = req.query;

    if (!startDate || !endDate) {
      sendResponse(res, 400, false, 'startDate and endDate are required');
      return;
    }

    const snapshot = await db.collection('users').doc(uid!)
      .collection('tasks')
      .where('date', '>=', startDate as string)
      .where('date', '<=', endDate as string)
      .get();

    const tasks = snapshot.docs.map(doc => doc.data());
    
    // Group by date
    const dailyStats: Record<string, { total: number, completed: number }> = {};
    
    tasks.forEach(task => {
      if (!dailyStats[task.date]) {
        dailyStats[task.date] = { total: 0, completed: 0 };
      }
      dailyStats[task.date].total += 1;
      if (task.status === 'completed') {
        dailyStats[task.date].completed += 1;
      }
    });

    const heatmapData = Object.keys(dailyStats).map(date => {
      const stats = dailyStats[date];
      return {
        date,
        total: stats.total,
        completed: stats.completed,
        completionPercentage: stats.total > 0 ? Math.round((stats.completed / stats.total) * 100) : 0
      };
    });

    sendResponse(res, 200, true, 'Heatmap data fetched successfully', heatmapData);
  } catch (error) {
    next(error);
  }
};
