"use client";

import { useEffect, useState, useMemo } from "react";
import api from "../../../lib/api";
import { useAuth } from "../../../context/AuthContext";
import {
  Calendar as CalendarIcon,
  CheckCircle2,
  Circle,
  Clock,
  Play,
  SkipForward,
  Plus,
  RefreshCw,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  Flame,
  Trophy,
  Zap,
  Target,
  Lock,
  X,
  Lightbulb
} from "lucide-react";

interface Task {
  id: string;
  title: string;
  category: string;
  priority: string;
  estimatedDuration: number;
  status: "pending" | "completed" | "skipped" | "rescheduled" | "incomplete";
  date: string;
  notes?: string;
  isAutoGenerated: boolean;
}

// Pure date helper utilities
function formatLocalDate(d: Date): string {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function normalizeToDate(val: any): Date | null {
  if (!val) return null;
  if (val instanceof Date) return isNaN(val.getTime()) ? null : val;
  if (typeof val?.toDate === "function") {
    try {
      const d = val.toDate();
      return isNaN(d?.getTime()) ? null : d;
    } catch {
      return null;
    }
  }
  if (typeof val?._seconds === "number") {
    const d = new Date(val._seconds * 1000);
    return isNaN(d.getTime()) ? null : d;
  }
  if (typeof val === "string") {
    const d = new Date(val);
    if (!isNaN(d.getTime())) return d;
    const parts = val.split("-").map(Number);
    if (parts.length === 3 && !isNaN(parts[0]) && !isNaN(parts[1]) && !isNaN(parts[2])) {
      return new Date(parts[0], parts[1] - 1, parts[2]);
    }
  }
  const fallback = new Date(val);
  return isNaN(fallback.getTime()) ? null : fallback;
}

function parseLocalDate(str: any): Date {
  if (!str) return new Date();
  if (typeof str === "string" && str.includes("-")) {
    const parts = str.split("T")[0].split("-").map(Number);
    if (parts.length === 3 && !isNaN(parts[0]) && !isNaN(parts[1]) && !isNaN(parts[2])) {
      return new Date(parts[0], parts[1] - 1, parts[2]);
    }
  }
  const d = normalizeToDate(str);
  return d || new Date();
}

export default function PlannerPage() {
  const { profile, refreshProfile } = useAuth();
  
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentDate, setCurrentDate] = useState<Date>(new Date());

  // Heatmap State
  interface HeatmapDayInfo {
    pct: number;
    total: number;
    completed: number;
  }
  const [heatmapData, setHeatmapData] = useState<Record<string, HeatmapDayInfo>>({});
  const [showStartDateModal, setShowStartDateModal] = useState(false);
  const [startDateInput, setStartDateInput] = useState("");
  const [isSettingStartDate, setIsSettingStartDate] = useState(false);
  const [heatmapYearFilter, setHeatmapYearFilter] = useState<string>(new Date().getFullYear().toString());

  // Task Action & Reschedule State
  const [activeDropdownTaskId, setActiveDropdownTaskId] = useState<string | null>(null);
  const [rescheduleModalTask, setRescheduleModalTask] = useState<Task | null>(null);
  const [rescheduleDateInput, setRescheduleDateInput] = useState("");
  const [isRescheduling, setIsRescheduling] = useState(false);

  // Modals state
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [techSkillInput, setTechSkillInput] = useState("");
  const [csConceptInput, setCsConceptInput] = useState("");

  const [newTask, setNewTask] = useState({
    title: "",
    category: "DSA",
    priority: "Medium",
    estimatedDuration: 60,
  });

  const formattedDate = formatLocalDate(currentDate);
  const todayStr = formatLocalDate(new Date());
  const isFuture = formattedDate > todayStr;
  const dayOfWeek = currentDate.getDay();

  const fetchTasks = async () => {
    setLoading(true);
    try {
      const res = await api.get(`/tasks?date=${formattedDate}`);
      setTasks(res.data.data || []);
    } catch (error) {
      console.error("Failed to fetch tasks:", error);
    } finally {
      setLoading(false);
    }
  };

  const fetchHeatmap = async (startDateStr: string, targetDateVal?: any) => {
    try {
      const queryStart = startDateStr;
      let queryEnd: string;
      const parsedTarget = normalizeToDate(targetDateVal);
      if (parsedTarget) {
        queryEnd = formatLocalDate(parsedTarget);
      } else {
        const d = parseLocalDate(startDateStr);
        d.setMonth(d.getMonth() + 4);
        queryEnd = formatLocalDate(d);
      }
      
      const res = await api.get(`/tasks/analytics/heatmap?startDate=${queryStart}&endDate=${queryEnd}`);
      const raw = res.data.data;
      const data = Array.isArray(raw) ? raw : (raw?.heatmap || []);
      const map: Record<string, HeatmapDayInfo> = {};
      data.forEach((d: any) => {
        map[d.date] = {
          pct: d.completionPercentage || 0,
          total: d.total || 0,
          completed: d.completed || 0
        };
      });
      setHeatmapData(map);
    } catch (e) {
      console.error("Failed to fetch heatmap data:", e);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, [currentDate]);

  useEffect(() => {
    if (profile !== null) {
      if (!profile.plannerStartDate) {
        if (!startDateInput) {
          setStartDateInput(formatLocalDate(new Date()));
        }
        setShowStartDateModal(true);
      } else {
        setShowStartDateModal(false);
        fetchHeatmap(profile.plannerStartDate, profile.targetDate);
      }
    }
  }, [profile]);

  const handleSetStartDate = async () => {
    if (!startDateInput || isSettingStartDate) return;
    setIsSettingStartDate(true);
    try {
      await api.patch("/users/me", { plannerStartDate: startDateInput });
      await refreshProfile();
      setShowStartDateModal(false);
    } catch (error) {
      console.error("Failed to set start date:", error);
      alert("Failed to lock start date. Please try again.");
    } finally {
      setIsSettingStartDate(false);
    }
  };

  const handleGeneratePlan = async () => {
    try {
      await api.post("/tasks/generate", {
        date: formattedDate,
        technicalSkill: techSkillInput || "React",
        csConcept: dayOfWeek === 0 ? csConceptInput : undefined,
      });
      setIsGenerateModalOpen(false);
      fetchTasks();
      if (profile?.plannerStartDate) {
        fetchHeatmap(profile.plannerStartDate, profile.targetDate);
      }
    } catch (error) {
      console.error("Failed to generate plan:", error);
      alert("Failed to generate plan. Please try again.");
    }
  };

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await api.post("/tasks", {
        ...newTask,
        date: formattedDate,
      });
      setIsCreateModalOpen(false);
      setNewTask({ title: "", category: "DSA", priority: "Medium", estimatedDuration: 60 });
      fetchTasks();
      if (profile?.plannerStartDate) {
        fetchHeatmap(profile.plannerStartDate, profile.targetDate);
      }
    } catch (error) {
      console.error("Failed to create task:", error);
    }
  };

  const updateTaskStatus = async (taskId: string, newStatus: string) => {
    if (isFuture && newStatus === "completed") {
      alert("Tasks can only be marked completed on the present day, not for future dates.");
      return;
    }

    // Optimistic update
    const updated = tasks.map(t => t.id === taskId ? { ...t, status: newStatus as any } : t);
    setTasks(updated);

    const total = updated.length;
    const completed = updated.filter(t => t.status === "completed").length;
    const pct = total > 0 ? Math.round((completed / total) * 100) : 0;
    setHeatmapData(prev => ({
      ...prev,
      [formattedDate]: { pct, total, completed }
    }));

    try {
      await api.put(`/tasks/${taskId}`, { status: newStatus });
    } catch (error) {
      console.error("Failed to update status:", error);
      fetchTasks();
      if (profile?.plannerStartDate) {
        fetchHeatmap(profile.plannerStartDate, profile.targetDate);
      }
    }
  };

  const handleConfirmReschedule = async () => {
    if (!rescheduleModalTask || !rescheduleDateInput) return;
    setIsRescheduling(true);
    try {
      await api.put(`/tasks/${rescheduleModalTask.id}`, {
        date: rescheduleDateInput,
        status: "pending"
      });
      setRescheduleModalTask(null);
      fetchTasks();
      if (profile?.plannerStartDate) {
        fetchHeatmap(profile.plannerStartDate, profile.targetDate);
      }
    } catch (error) {
      console.error("Failed to reschedule task:", error);
      alert("Failed to reschedule task. Please try again.");
    } finally {
      setIsRescheduling(false);
    }
  };

  const changeDate = (days: number) => {
    const nextDate = new Date(currentDate);
    nextDate.setDate(currentDate.getDate() + days);
    setCurrentDate(nextDate);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "completed": return "text-emerald-500 bg-emerald-50 border-emerald-200";
      case "skipped": return "text-slate-400 bg-slate-50 border-slate-200";
      case "rescheduled": return "text-amber-500 bg-amber-50 border-amber-200";
      case "incomplete": return "text-rose-500 bg-rose-50 border-rose-200";
      default: return "text-indigo-500 bg-white border-slate-200";
    }
  };

  const getCategoryColor = (category: string) => {
    switch (category) {
      case "DSA": return "bg-rose-100 text-rose-700";
      case "Technical Skill": return "bg-blue-100 text-blue-700";
      case "Aptitude": return "bg-amber-100 text-amber-700";
      case "CS Fundamentals": return "bg-purple-100 text-purple-700";
      case "Project": return "bg-emerald-100 text-emerald-700";
      case "Revision": return "bg-indigo-100 text-indigo-700";
      default: return "bg-slate-100 text-slate-700";
    }
  };

  const totalTasks = tasks.length;
  const completedTasks = tasks.filter(t => t.status === "completed").length;
  const progress = totalTasks === 0 ? 0 : Math.round((completedTasks / totalTasks) * 100);

  // Calculate Streak and Stats
  const streakStats = useMemo(() => {
    if (!profile?.plannerStartDate) {
      return { currentStreak: 0, highestStreak: 0, totalActiveDays: 0 };
    }

    const startDate = parseLocalDate(profile.plannerStartDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const isActive = (dateStr: string) => {
      const d = heatmapData[dateStr];
      if (!d) return false;
      return d.pct > 0 || d.completed > 0;
    };

    let totalActiveDays = 0;
    let highestStreak = 0;
    let runningStreak = 0;

    // Scan day by day from startDate to today
    const iter = new Date(startDate);
    while (iter <= today) {
      const dStr = formatLocalDate(iter);
      if (isActive(dStr)) {
        totalActiveDays++;
        runningStreak++;
        if (runningStreak > highestStreak) {
          highestStreak = runningStreak;
        }
      } else {
        runningStreak = 0;
      }
      iter.setDate(iter.getDate() + 1);
    }

    // Current streak calculation
    const todayStr = formatLocalDate(today);
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const yesterdayStr = formatLocalDate(yesterday);

    let currentStreak = 0;
    let checkDate: Date | null = null;

    if (isActive(todayStr)) {
      checkDate = new Date(today);
    } else if (isActive(yesterdayStr)) {
      checkDate = new Date(yesterday);
    }

    if (checkDate) {
      while (checkDate >= startDate) {
        const dStr = formatLocalDate(checkDate);
        if (isActive(dStr)) {
          currentStreak++;
          checkDate.setDate(checkDate.getDate() - 1);
        } else {
          break;
        }
      }
    }

    return { currentStreak, highestStreak, totalActiveDays };
  }, [profile?.plannerStartDate, heatmapData]);

  const renderHeatmap = () => {
    if (!profile?.plannerStartDate) return null;

    const startDate = parseLocalDate(profile.plannerStartDate);
    const parsedTarget = normalizeToDate(profile?.targetDate);
    let targetDate = (parsedTarget && !isNaN(parsedTarget.getTime()))
      ? parsedTarget
      : (() => {
          const d = new Date(startDate);
          d.setMonth(d.getMonth() + 4);
          return d;
        })();

    if (targetDate < startDate) {
      const d = new Date(startDate);
      d.setMonth(d.getMonth() + 4);
      targetDate = d;
    }

    const sYear = startDate.getFullYear();
    const sMonth = startDate.getMonth();
    const tYear = targetDate.getFullYear();
    const tMonth = targetDate.getMonth();
    const currentYear = new Date().getFullYear();

    // Determine filter options
    const yearOptions: { value: string; label: string }[] = [];
    for (let y = sYear; y <= Math.max(sYear, tYear); y++) {
      yearOptions.push({
        value: y.toString(),
        label: y === currentYear ? `${y} (Current)` : `${y}`
      });
    }
    yearOptions.push({
      value: "All",
      label: "All Time"
    });

    const validFilterValues = yearOptions.map(o => o.value);
    const activeFilter = validFilterValues.includes(heatmapYearFilter) 
      ? heatmapYearFilter 
      : (validFilterValues.includes(currentYear.toString()) ? currentYear.toString() : validFilterValues[0]);

    // Build month blocks
    const monthBlocks: {
      label: string;
      mYear: number;
      mMonth: number;
      weeks: Date[][];
    }[] = [];

    if (activeFilter === "All") {
      const totalMonths = (tYear - sYear) * 12 + (tMonth - sMonth) + 1;
      const count = Math.max(1, totalMonths);
      for (let i = 0; i < count; i++) {
        const mDate = new Date(sYear, sMonth + i, 1);
        const mYear = mDate.getFullYear();
        const mMonth = mDate.getMonth();

        const firstDayOfMonth = new Date(mYear, mMonth, 1);
        const lastDayOfMonth = new Date(mYear, mMonth + 1, 0);

        const firstGrid = new Date(firstDayOfMonth);
        firstGrid.setDate(firstGrid.getDate() - firstGrid.getDay());

        const lastGrid = new Date(lastDayOfMonth);
        if (lastGrid.getDay() !== 6) {
          lastGrid.setDate(lastGrid.getDate() + (6 - lastGrid.getDay()));
        }

        const weeks: Date[][] = [];
        let curr = new Date(firstGrid);
        while (curr <= lastGrid) {
          if (curr.getDay() === 0) weeks.push([]);
          weeks[weeks.length - 1].push(new Date(curr));
          curr.setDate(curr.getDate() + 1);
        }

        monthBlocks.push({
          label: `${mDate.toLocaleDateString("en-US", { month: "short" })} '${String(mYear).slice(2)}`,
          mYear,
          mMonth,
          weeks
        });
      }
    } else {
      const selYear = parseInt(activeFilter);
      const fromMonth = (selYear === sYear) ? sMonth : 0;
      const toMonth = (selYear === tYear) ? tMonth : 11;
      const count = Math.max(1, toMonth - fromMonth + 1);

      for (let i = 0; i < count; i++) {
        const mDate = new Date(selYear, fromMonth + i, 1);
        const mYear = mDate.getFullYear();
        const mMonth = mDate.getMonth();

        const firstDayOfMonth = new Date(mYear, mMonth, 1);
        const lastDayOfMonth = new Date(mYear, mMonth + 1, 0);

        const firstGrid = new Date(firstDayOfMonth);
        firstGrid.setDate(firstGrid.getDate() - firstGrid.getDay());

        const lastGrid = new Date(lastDayOfMonth);
        if (lastGrid.getDay() !== 6) {
          lastGrid.setDate(lastGrid.getDate() + (6 - lastGrid.getDay()));
        }

        const weeks: Date[][] = [];
        let curr = new Date(firstGrid);
        while (curr <= lastGrid) {
          if (curr.getDay() === 0) weeks.push([]);
          weeks[weeks.length - 1].push(new Date(curr));
          curr.setDate(curr.getDate() + 1);
        }

        monthBlocks.push({
          label: mDate.toLocaleDateString("en-US", { month: "short" }),
          mYear,
          mMonth,
          weeks
        });
      }
    }

    const getHeatmapColor = (pct: number) => {
      if (pct === 0) return "bg-slate-100 hover:bg-slate-200";
      if (pct <= 20) return "bg-emerald-200 hover:bg-emerald-300";
      if (pct <= 40) return "bg-emerald-300 hover:bg-emerald-400";
      if (pct <= 60) return "bg-emerald-400 hover:bg-emerald-500";
      if (pct <= 80) return "bg-emerald-500 hover:bg-emerald-600";
      return "bg-emerald-600 hover:bg-emerald-700";
    };

    return (
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 mb-6">
        {/* Top Header & Stats */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-4 border-b border-slate-100 mb-5">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-xl">
              <CalendarIcon className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-slate-900">Activity Heatmap</h2>
                <span className="flex items-center gap-1 text-[11px] font-semibold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full">
                  <Lock className="w-3 h-3 text-slate-400" /> Start Locked
                </span>
              </div>
              <p className="text-xs text-slate-500 font-medium">
                Preparation timeline: {startDate.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} → {targetDate.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            {/* Current Streak */}
            <div className="flex items-center gap-2 px-3 py-1.5 bg-orange-50 border border-orange-200/80 rounded-xl shadow-xs">
              <Flame className="w-4 h-4 text-orange-500 fill-orange-500 animate-pulse" />
              <div>
                <div className="text-[10px] uppercase font-bold tracking-wider text-orange-600 leading-tight">Current Streak</div>
                <div className="text-sm font-extrabold text-orange-950 leading-tight">
                  {streakStats.currentStreak} {streakStats.currentStreak === 1 ? "day" : "days"}
                </div>
              </div>
            </div>

            {/* Highest Streak */}
            <div className="flex items-center gap-2 px-3 py-1.5 bg-amber-50 border border-amber-200/80 rounded-xl shadow-xs">
              <Trophy className="w-4 h-4 text-amber-500 fill-amber-400/30" />
              <div>
                <div className="text-[10px] uppercase font-bold tracking-wider text-amber-600 leading-tight">Highest Streak</div>
                <div className="text-sm font-extrabold text-amber-950 leading-tight">
                  {streakStats.highestStreak} {streakStats.highestStreak === 1 ? "day" : "days"}
                </div>
              </div>
            </div>

            {/* Active Days */}
            <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-50 border border-emerald-200/80 rounded-xl shadow-xs">
              <Zap className="w-4 h-4 text-emerald-500 fill-emerald-500" />
              <div>
                <div className="text-[10px] uppercase font-bold tracking-wider text-emerald-600 leading-tight">Active Days</div>
                <div className="text-sm font-extrabold text-emerald-950 leading-tight">
                  {streakStats.totalActiveDays} {streakStats.totalActiveDays === 1 ? "day" : "days"}
                </div>
              </div>
            </div>

            {/* Year Filter Dropdown */}
            <div className="flex items-center gap-1.5 pl-1">
              <select
                value={activeFilter}
                onChange={(e) => setHeatmapYearFilter(e.target.value)}
                className="text-xs font-semibold bg-white border border-slate-200 rounded-xl px-3 py-2 text-slate-700 hover:border-slate-300 focus:ring-2 focus:ring-indigo-500 focus:outline-none cursor-pointer shadow-xs transition-colors"
              >
                {yearOptions.map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>
          </div>
        </div>

        {/* Heatmap Grid Container (Scrollable horizontally) */}
        <div className="overflow-x-auto pb-3 pt-1">
          <div className="flex items-start gap-6 min-w-max">
            {/* Weekday indicators */}
            <div className="flex flex-col gap-1 text-[10px] text-slate-400 font-semibold pt-7 pr-1 select-none">
              <span className="h-3.5 leading-[14px]">Sun</span>
              <span className="h-3.5 leading-[14px]">Mon</span>
              <span className="h-3.5 leading-[14px]">Tue</span>
              <span className="h-3.5 leading-[14px]">Wed</span>
              <span className="h-3.5 leading-[14px]">Thu</span>
              <span className="h-3.5 leading-[14px]">Fri</span>
              <span className="h-3.5 leading-[14px]">Sat</span>
            </div>

            {/* Month blocks */}
            {monthBlocks.map((block, bIndex) => (
              <div key={bIndex} className="flex flex-col items-center gap-2">
                {/* Centered Month label */}
                <span className="text-xs font-bold text-slate-600 tracking-wide h-5 flex items-center">
                  {block.label}
                </span>

                {/* Week columns */}
                <div className="flex gap-1">
                  {block.weeks.map((week, wIndex) => (
                    <div key={wIndex} className="flex flex-col gap-1">
                      {week.map((date, dIndex) => {
                        const dateStr = formatLocalDate(date);
                        const isCurrentMonth = date.getMonth() === block.mMonth;
                        const isBeforeStart = date < startDate;
                        const isAfterTarget = date > targetDate;
                        const isOut = isBeforeStart || isAfterTarget;

                        if (!isCurrentMonth) {
                          return (
                            <div 
                              key={dIndex} 
                              className="w-3.5 h-3.5 rounded-[3px] opacity-0 pointer-events-none" 
                            />
                          );
                        }

                        if (isOut) {
                          return (
                            <div
                              key={dIndex}
                              title={`${dateStr} (Outside roadmap)`}
                              className="w-3.5 h-3.5 rounded-[3px] bg-slate-100 opacity-30 cursor-not-allowed"
                            />
                          );
                        }

                        const dayData = heatmapData[dateStr];
                        const pct = dayData ? dayData.pct : 0;
                        const isSelected = dateStr === formattedDate;

                        const tooltip = dayData && dayData.total > 0
                          ? `${date.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" })}: ${dayData.completed}/${dayData.total} tasks completed (${pct}%)`
                          : `${date.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" })}: No tasks recorded (0%)`;

                        return (
                          <div
                            key={dIndex}
                            onClick={() => setCurrentDate(new Date(date))}
                            title={tooltip}
                            className={`w-3.5 h-3.5 rounded-[3px] transition-all cursor-pointer ${getHeatmapColor(pct)} ${
                              isSelected 
                                ? "ring-2 ring-indigo-600 ring-offset-1 z-10 scale-110 shadow-xs" 
                                : "hover:scale-125 hover:z-20 hover:shadow-xs"
                            }`}
                          />
                        );
                      })}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Legend & Hint */}
        <div className="flex flex-wrap items-center justify-between gap-4 mt-3 pt-3 border-t border-slate-100 text-xs text-slate-500">
          <span className="text-[11px] text-slate-400 flex items-center gap-1.5">
            <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
            <span>Tip: Click any square on the heatmap to open and edit tasks for that date.</span>
          </span>
          <div className="flex items-center gap-1.5 select-none">
            <span className="text-[11px] text-slate-400 mr-1">Less</span>
            <div className="w-3 h-3 rounded-[2px] bg-slate-100" title="0%" />
            <div className="w-3 h-3 rounded-[2px] bg-emerald-200" title="1-20%" />
            <div className="w-3 h-3 rounded-[2px] bg-emerald-300" title="21-40%" />
            <div className="w-3 h-3 rounded-[2px] bg-emerald-400" title="41-60%" />
            <div className="w-3 h-3 rounded-[2px] bg-emerald-500" title="61-80%" />
            <div className="w-3 h-3 rounded-[2px] bg-emerald-600" title="81-100%" />
            <span className="text-[11px] text-slate-400 ml-1">More</span>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12 animate-in fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row gap-6 justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
        <div className="flex items-center gap-4">
          <button onClick={() => changeDate(-1)} className="p-2 hover:bg-slate-100 rounded-full transition-colors">
            <ChevronLeft className="w-5 h-5 text-slate-600" />
          </button>
          <div className="flex flex-col items-center min-w-[150px]">
            <h1 className="text-xl font-bold font-display text-slate-900">
              {currentDate.toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}
            </h1>
            <p className="text-sm text-slate-500">
              {currentDate.toDateString() === new Date().toDateString() ? "Today" : ""}
            </p>
          </div>
          <button onClick={() => changeDate(1)} className="p-2 hover:bg-slate-100 rounded-full transition-colors">
            <ChevronRight className="w-5 h-5 text-slate-600" />
          </button>
        </div>

        <div className="flex items-center gap-6 w-full md:w-auto">
          <div className="flex flex-col items-end flex-1 md:flex-none">
            <div className="flex justify-between w-full mb-1">
              <span className="text-sm font-semibold text-slate-600">Daily Progress</span>
              <span className="text-sm font-bold text-indigo-600">{progress}%</span>
            </div>
            <div className="w-full md:w-48 h-2.5 bg-slate-100 rounded-full overflow-hidden">
              <div 
                className="h-full bg-indigo-600 rounded-full transition-all duration-500 ease-out"
                style={{ width: `${progress}%` }}
              ></div>
            </div>
          </div>
          
          <button
            onClick={() => setIsCreateModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium transition-colors shadow-sm whitespace-nowrap"
          >
            <Plus className="w-4 h-4" />
            Add Task
          </button>
        </div>
      </div>

      {/* Heatmap */}
      {renderHeatmap()}

      {/* Task List Content */}
      {isFuture && tasks.length > 0 && (
        <div className="flex items-center gap-2.5 px-4 py-3 bg-amber-50 border border-amber-200/80 rounded-xl text-xs text-amber-800 font-medium">
          <Clock className="w-4 h-4 text-amber-600 shrink-0" />
          <span>
            <strong>Future Planning:</strong> You can assign, create, and reschedule tasks for future dates. Tasks can only be marked completed on the present day.
          </span>
        </div>
      )}

      {loading ? (
        <div className="flex justify-center py-20">
          <div className="w-8 h-8 rounded-full border-2 border-indigo-600 border-t-transparent animate-spin"></div>
        </div>
      ) : tasks.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-200 p-12 flex flex-col items-center justify-center text-center shadow-sm">
          <div className="w-16 h-16 bg-indigo-50 rounded-2xl flex items-center justify-center text-indigo-600 mb-4">
            <CalendarIcon className="w-8 h-8" />
          </div>
          <h2 className="text-xl font-bold text-slate-900 mb-2">No tasks scheduled for this day</h2>
          <p className="text-slate-500 max-w-md mb-6">
            The Phase 4 engine can automatically generate a balanced daily plan including DSA, Technical Skills, and Aptitude based on the One-Week One-Skill approach.
          </p>
          <button
            onClick={() => setIsGenerateModalOpen(true)}
            className="flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-semibold transition-colors shadow-sm"
          >
            <Play className="w-4 h-4" />
            Generate Daily Plan
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {tasks.map((task) => (
            <div 
              key={task.id} 
              className={`flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center p-4 bg-white rounded-xl border transition-all shadow-sm ${getStatusColor(task.status)}`}
            >
              <div className="flex items-start gap-4">
                <button 
                  disabled={isFuture}
                  onClick={() => {
                    if (isFuture) return;
                    updateTaskStatus(task.id, task.status === "completed" ? "pending" : "completed");
                  }}
                  title={isFuture ? "Tasks can only be marked completed on the present day" : undefined}
                  className={`mt-1 flex-shrink-0 transition-transform ${
                    isFuture ? "cursor-not-allowed opacity-40" : "active:scale-90 cursor-pointer"
                  }`}
                >
                  {task.status === "completed" ? (
                    <CheckCircle2 className="w-6 h-6 text-emerald-500" />
                  ) : task.status === "skipped" ? (
                    <SkipForward className="w-6 h-6 text-slate-400" />
                  ) : task.status === "rescheduled" ? (
                    <RefreshCw className="w-6 h-6 text-amber-500" />
                  ) : (
                    <Circle className={`w-6 h-6 ${isFuture ? "text-slate-300" : "text-slate-300 hover:text-indigo-400"}`} />
                  )}
                </button>
                
                <div>
                  <h3 className={`font-semibold text-lg ${task.status === "completed" || task.status === "skipped" ? "line-through opacity-70" : "text-slate-900"}`}>
                    {task.title}
                  </h3>
                  <div className="flex flex-wrap items-center gap-3 mt-1.5">
                    <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-md ${getCategoryColor(task.category)}`}>
                      {task.category}
                    </span>
                    <div className="flex items-center gap-1 text-xs text-slate-500 font-medium">
                      <Clock className="w-3.5 h-3.5" />
                      {task.estimatedDuration} mins
                    </div>
                    {task.priority === "High" && (
                      <div className="flex items-center gap-1 text-xs text-rose-500 font-medium bg-rose-50 px-1.5 py-0.5 rounded">
                        <TrendingUp className="w-3 h-3" />
                        High Priority
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Dropdown Menu via Three Dots */}
              <div className="relative self-end sm:self-auto">
                <button 
                  onClick={(e) => {
                    e.stopPropagation();
                    setActiveDropdownTaskId(activeDropdownTaskId === task.id ? null : task.id);
                  }}
                  className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors cursor-pointer"
                  title="Task Options"
                >
                  <MoreVertical className="w-4 h-4" />
                </button>

                {activeDropdownTaskId === task.id && (
                  <>
                    <div 
                      className="fixed inset-0 z-20" 
                      onClick={() => setActiveDropdownTaskId(null)} 
                    />
                    <div className="absolute right-0 mt-1 w-44 bg-white rounded-xl shadow-lg border border-slate-100 py-1.5 z-30 animate-in fade-in zoom-in-95">
                      <button
                        onClick={() => {
                          setActiveDropdownTaskId(null);
                          setRescheduleModalTask(task);
                          const tomorrow = new Date(currentDate);
                          tomorrow.setDate(tomorrow.getDate() + 1);
                          setRescheduleDateInput(formatLocalDate(tomorrow));
                        }}
                        className="w-full flex items-center gap-2.5 px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-indigo-50 hover:text-indigo-600 transition-colors text-left cursor-pointer"
                      >
                        <RefreshCw className="w-3.5 h-3.5 text-slate-400" />
                        Reschedule
                      </button>
                      <button
                        onClick={() => {
                          setActiveDropdownTaskId(null);
                          updateTaskStatus(task.id, task.status === "skipped" ? "pending" : "skipped");
                        }}
                        className="w-full flex items-center gap-2.5 px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors text-left cursor-pointer"
                      >
                        <SkipForward className="w-3.5 h-3.5 text-slate-400" />
                        {task.status === "skipped" ? "Unskip" : "Skip"}
                      </button>
                    </div>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Generate Modal */}
      {isGenerateModalOpen && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-xl animate-in zoom-in-95">
            <h2 className="text-xl font-bold text-slate-900 mb-2">Generate Daily Plan</h2>
            <p className="text-sm text-slate-500 mb-6">
              Following the "One Week – One Technical Skill" approach.
            </p>
            
            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">
                  Focus Technical Skill for this week
                </label>
                <input
                  type="text"
                  placeholder="e.g., React, Node.js, Docker"
                  value={techSkillInput}
                  onChange={(e) => setTechSkillInput(e.target.value)}
                  className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                />
              </div>

              {dayOfWeek === 0 && (
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">
                    Core CS Concept (Sunday Revision)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g., OS, DBMS, Computer Networks"
                    value={csConceptInput}
                    onChange={(e) => setCsConceptInput(e.target.value)}
                    className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                  />
                </div>
              )}
            </div>

            <div className="flex justify-end gap-3">
              <button
                onClick={() => setIsGenerateModalOpen(false)}
                className="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleGeneratePlan}
                disabled={!techSkillInput}
                className="px-4 py-2 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl transition-colors disabled:opacity-50"
              >
                Generate Tasks
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Create Task Modal */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-xl animate-in zoom-in-95">
            <h2 className="text-xl font-bold text-slate-900 mb-6">Add Custom Task</h2>
            
            <form onSubmit={handleCreateTask} className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Task Title</label>
                <input
                  type="text"
                  required
                  value={newTask.title}
                  onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">Category</label>
                  <select
                    value={newTask.category}
                    onChange={(e) => setNewTask({ ...newTask, category: e.target.value })}
                    className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                  >
                    <option value="DSA">DSA</option>
                    <option value="Technical Skill">Technical Skill</option>
                    <option value="Aptitude">Aptitude</option>
                    <option value="CS Fundamentals">CS Fundamentals</option>
                    <option value="Project">Project</option>
                    <option value="Revision">Revision</option>
                    <option value="Optional">Optional</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">Duration (mins)</label>
                  <input
                    type="number"
                    required
                    min="5"
                    step="5"
                    value={newTask.estimatedDuration}
                    onChange={(e) => setNewTask({ ...newTask, estimatedDuration: parseInt(e.target.value) })}
                    className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Priority</label>
                <select
                  value={newTask.priority}
                  onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}
                  className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600"
                >
                  <option value="Low">Low</option>
                  <option value="Medium">Medium</option>
                  <option value="High">High</option>
                </select>
              </div>

              <div className="flex justify-end gap-3 mt-8">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl transition-colors"
                >
                  Add Task
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Start Date Modal */}
      {showStartDateModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-2xl border border-slate-100 animate-in zoom-in-95">
            <div className="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center text-indigo-600 mb-4">
              <CalendarIcon className="w-6 h-6" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 mb-1.5">Set Preparation Start Date</h2>
            <p className="text-sm text-slate-500 mb-4 leading-relaxed">
              To track your daily study activity heatmap through your target placement date, please choose your starting date.
            </p>

            <div className="bg-amber-50 border border-amber-200/80 rounded-xl p-3.5 mb-5 flex items-start gap-2.5">
              <Lock className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
              <div className="text-xs text-amber-900 leading-relaxed font-medium">
                <strong>Permanent Setting:</strong> Once submitted, your start date is locked and cannot be edited.
              </div>
            </div>
            
            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                  Start Date
                </label>
                <input
                  type="date"
                  value={startDateInput}
                  onChange={(e) => setStartDateInput(e.target.value)}
                  className="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-slate-800 font-medium focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600 outline-none"
                />
              </div>
            </div>

            <div className="flex justify-end">
              <button
                onClick={handleSetStartDate}
                disabled={!startDateInput || isSettingStartDate}
                className="w-full px-4 py-2.5 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl transition-colors disabled:opacity-50 flex items-center justify-center gap-2 shadow-sm"
              >
                {isSettingStartDate ? "Locking Start Date..." : "Confirm & Lock Start Date"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Reschedule Task Modal */}
      {rescheduleModalTask && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-xl border border-slate-100 animate-in zoom-in-95">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2.5">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
                  <RefreshCw className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900">Reschedule Task</h2>
                  <p className="text-xs text-slate-500">Mention the date to move this task to</p>
                </div>
              </div>
              <button 
                onClick={() => setRescheduleModalTask(null)}
                className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3.5 mb-5">
              <div className="text-sm font-semibold text-slate-800 truncate">{rescheduleModalTask.title}</div>
              <div className="text-xs text-slate-500 mt-1">
                Currently scheduled on: <strong className="text-slate-700">{rescheduleModalTask.date}</strong> • {rescheduleModalTask.category}
              </div>
            </div>

            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                  Target Reschedule Date
                </label>
                <input
                  type="date"
                  required
                  value={rescheduleDateInput}
                  onChange={(e) => setRescheduleDateInput(e.target.value)}
                  className="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-slate-800 font-medium focus:ring-2 focus:ring-indigo-600 focus:border-indigo-600 outline-none"
                />
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setRescheduleModalTask(null)}
                className="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition-colors cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmReschedule}
                disabled={!rescheduleDateInput || isRescheduling}
                className="px-5 py-2 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl transition-colors disabled:opacity-50 flex items-center gap-2 shadow-sm cursor-pointer"
              >
                {isRescheduling ? "Rescheduling..." : "Confirm Reschedule"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
